spring.datasource.url=jdbc:postgresql://dpg-d75nn1s50q8c73b50r4g-a:5432/railway_c1zw
spring.datasource.username=railway_c1zw_user
spring.datasource.password=CVKOhW5rBJESfyIbB3CCvOAsToYxNu8r
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Spring Boot automatically uses the DATABASE_URL environment variable from Render
# to configure the data source, so you don't need to set the URL, username, or password here.

# This sets the hibernate ddl-auto property. 'update' will update the schema if needed.
spring.jpa.hibernate.ddl-auto=update

# Render provides the port to use via the PORT environment variable.
# This tells Spring Boot to use that port, defaulting to 8080 if not set.
server.port=${PORT:8080}